name: rick_and_morty
description: A new Flutter project.


publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"


dependencies:
  badges: ^3.0.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  dynamic_color: ^1.6.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.8.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  lottie: ^2.3.0
  path_provider: ^2.0.14
  smooth_page_indicator: ^1.1.0



dev_dependencies:
  build_runner: ^2.3.3


  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1


flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
