name: rick_and_morty
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" #this is for the signup bloc 
  #sdk: ">=2.18.6 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  badges: ^3.0.3
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  dynamic_color: ^1.6.6
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.1.0 # this was in the pubspec of the bloc auth example, check if can be removed
  flutter_screenutil: ^5.8.4
  formz: ^0.6.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  lottie: ^2.3.0
  path_provider: ^2.0.14
  smooth_page_indicator: ^1.1.0
  meta: ^1.7.0 # this was in the pubspec of the bloc auth example, check if can be removed

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
